### ISSUE TITLE
Csrf does not work on port 3000

### ISSUE THREAD

**Issue by davidsoderberg** [anheru88/laravel-elixir-browser-sync#1]
Hi, I have my artisan server running on 8000 and when I run browser sync on 3000 it does not work with input or csrf, why?

**Comment by anheru88** [comment]
Hi, pleace can you share your code.

**Comment by davidsoderberg** [comment]
```
elixir(function(mix) {
    mix.BrowserSync(
    {
        proxy           : "localhost:8000"
    });
});
```

**Comment by anheru88** [comment]
You use php artisan server first? And you configure your local enviroment, for using mysql? I don't understand your error.

**Comment by davidsoderberg** [comment]
Yes my local enviorment works on 8000 but when I visit 3000 and try to submit a form I get tokenmismatchexception...

**Comment by anheru88** [comment]
Pleace first install the last version of laravel-elixir-browser, secod update your composer dependencies, if not working, can you share one pic show the problem, share your routes file - Only the method put -, and share your controller class.

**Comment by davidsoderberg** [comment]
Update to the last version did fix it :smile:
