### ISSUE TITLE
Run BrowserSync only on 'gulp watch'

### ISSUE THREAD

**Issue by willemvb** [anheru88/laravel-elixir-browser-sync#2]
Hi,

Is there a way to run BrowserSync only when using `gulp watch` and not on `gulp`? 

thanks,
Willem

**Comment by anheru88** [comment]
Hello My friend, thanks for you issue, I fixed the problem right now.

The documentantion change, please read againg and enjoy.

Thanks,

Angel

**Comment by willemvb** [comment]
Thanks!
