### ISSUE TITLE
Not actually refreshing browser

### ISSUE THREAD

**Issue by mdunbavan** [anheru88/laravel-elixir-browser-sync#3]
Hi,

Having set the plugin up on my laravel vagrant box site I cannot get it to work:

gulpfile.js

```
process.env.DISABLE_NOTIFIER = true;
var gulp = require('gulp');
var elixir = require('laravel-elixir');
var BrowserSync = require('laravel-elixir-browsersync');
require('laravel-elixir-uglify');


/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */


elixir(function(mix) {
    BrowserSync.init();
    mix.sass('app.scss', null, { includePaths: ['resources/assets/partials','resources/assets/bourbon'] });
    mix.scripts([
        'main.js',
        'app.js'
    ]).uglify('**/*.js', 'public/js', {
        mangle: true,
        suffix: '.min'
    });
    mix.BrowserSync(
    {
        proxy           : "synergycamps.dev",
        logPrefix       : "Laravel Eixir BrowserSync",
        logConnections  : false,
        reloadOnRestart : false,
        notify          : false
    });
});
```

Then my app in hosts file runs off this:

```
192.168.10.10 synergycamps.dev
```

Is this related to vagrant at all?

**Comment by anheru88** [comment]
Hi @mdunbavan please give me what version of laravel, and elixir you use, and second, you run gulp watch or gulp. The actualy version V0.1.3 only work using gulp watch, and you need to run in your pc, no inside the vagrant box.

And you need configurate before the domain, in the host file, and in your vagrant box.

Right now i try to fix many problems, becouse the las week laravel update Elixir, and all plugins not found.

I waiting your answer.

**Comment by mdunbavan** [comment]
@anheru88 Its laravel 5.1 and elixir 2 and I do run gulp watch as said in the docs

**Comment by anheru88** [comment]
@mdunbavan Hi, sorry for the delay, i fix the problem, please you can update your pacakage for the Version 0.1.5, If you use Laravel 5.1 and Elixir 3 - Please use [this](https://github.com/anheru88/laravel-elixir-browser-sync2) new package, the documentation is update.
